
[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.normal]
family = "ShureTechMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "PageUp"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "PageDown"

[window]
opacity = 0.95
blur = true
padding = {x = 5, y = 5}

[general]
import = ["~/.config/alacritty/gruvbox_dark.toml"]
